flathub/org.nongnu.gsequencer.gsequencer

org.nongnu.gsequencer.gsequencer.json
patches/gsequencer-app-stream-release.patch

* improved ags_soundcard_editor_reset() to set backend properly
* improved mutexes

new upstream v2.1.76

---

org.nongnu.gsequencer.gsequencer.json
patches/gsequencer-app-stream-release.patch

new upstream v2.1.77

---

org.nongnu.gsequencer.gsequencer.json

* improved check if lv2 plugin port already added

new upstream v2.2.7

---

org.nongnu.gsequencer.gsequencer.json

* improved LV2 logarithmic ports

new upstream v2.2.9

---

.flatpak-builder/ccache/disabled/ccache.conf
org.nongnu.gsequencer.gsequencer.json

Added some LADSPA and LV2 plugins

---

org.nongnu.gsequencer.gsequencer.json

* fixed race-condition ended in a dead-lock

new upstream v2.2.17

---

org.nongnu.gsequencer.gsequencer.json

* refactored AgsLv2Bridge and AgsLiveLv2Bridge

new upstream v2.2.19

---

org.nongnu.gsequencer.gsequencer.json

* implemented gui-scale configuration key in generic group

new upstream v2.2.20

---

org.nongnu.gsequencer.gsequencer.json

* implemented gui-scale configuration key

new upstream v2.2.22

---

org.nongnu.gsequencer.gsequencer.json

* replaced hard-coded fonts
* fixed timing issue

new upstream v2.2.23

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.2.27

---

org.nongnu.gsequencer.gsequencer.json

* fixed dead-lock related to Pulseaudio

new upstream v2.2.28

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.2.31

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.2.33

---

org.nongnu.gsequencer.gsequencer.json

* implemented AgsFMSynth
* implemented AgsFMSyncSynth
* implemented AgsFMOscillator
* implemented AgsPitchSampler and AgsPitchSamplerFile
* implemented AgsSFZFile, AgsSFZGroup, AgsSFZRegion and AgsSFZSample
* implemented AgsSFZLoader
* implemented ags-lfo recall
* implemented AgsComplex buffer type
* implemented AgsFrequencyMapManager
* implemented AgsFrequencyMap to compute max likelihood
* implemented ags_fm_synth_util.h supporting FM synthesis
* implemented ags_lfo_synth_util.h supporting LFO amplification
* implemented ags_fourier_transform_util.c
* implemented ags_filter_util.c
* extended ags_simple_file.c
* extended ags_audio_buffer_util.h to support complex data type
* extended ags_synth_util.h to support complex data type
* extended ags_synth_util.h to support impulse oscillator
* …

new upstream v2.3.1

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.3.13

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.3.15

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.4.1

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.4.2

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.4.3

---

org.nongnu.gsequencer.gsequencer.json

* sorted alphabetically plugins in AgsPluginBrowser

new upstream v2.4.5

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.4.6

---

org.nongnu.gsequencer.gsequencer.json

new upstream v2.4.8

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV
* fixed potential data-race

new upstream v3.0.4

---

org.nongnu.gsequencer.gsequencer.json

* implemented meta widgets
* updated user's manual
* fixed automation editor not showing after machine changed

new upstream v3.1.1

---

org.nongnu.gsequencer.gsequencer.json

* disabled GMainLoop integration of AgsTaskLauncher in AgsXorgApplicationContext

new upstream v3.2.0

---

org.nongnu.gsequencer.gsequencer.json

* implemented AgsLv2TurtleScanner quick scan

new upstream v3.2.8

---

org.nongnu.gsequencer.gsequencer.json

* faster AgsMachineEditor load

new upstream v3.2.10

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential NULL pointer dereference
* fixed wrong midi-end-mapping of AgsSimpleFile

new upstream v3.2.14

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.2.15

---

org.nongnu.gsequencer.gsequencer.json

This fix syntax errors in the manifest. flatpak-builder was complaining.

Fix manifest syntax

---

org.nongnu.gsequencer.gsequencer.json

All that stuff can be built using shared-modules now.

Use shared modules to build

---

org.nongnu.gsequencer.gsequencer.json

* implemented new ags-fx engine

new upstream v3.3.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed infinite loop
* fixed pointer corruption because of wrong cast

new upstream v3.3.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed MIDI input
* fixed AgsSyncsynth and AgsFmSyncsynth playback

new upstream v3.3.4

---

org.nongnu.gsequencer.gsequencer.json

* fixed MIDI
* fixed potential SIGSEGV in AgsSpectrometer

new upstream v3.3.6

---

org.nongnu.gsequencer.gsequencer.json

Now that CMT is packaged as a flatpak
Let's use that.

Install LADSPA CMT from flathub

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.3.8

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.3.9

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.3.10

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing automation of ags-fx-volume

new upstream v3.3.13

---

org.nongnu.gsequencer.gsequencer.json

* improved AgsAutomationEditor
* added ags-fx-volume to AgsPanel

new upstream v3.3.14

---

org.nongnu.gsequencer.gsequencer.json

* fixes to ags-fx-ladspa and ags-fx-lv2

new upstream v3.3.16

---

org.nongnu.gsequencer.gsequencer.json

* implemented SF2 and SFZ synth generator allowing you to pitch missing samples

new upstream v3.4.2

---

org.nongnu.gsequencer.gsequencer.json

* improved filter util to use projection during 2nd pitch rewrite

new upstream v3.4.5

---

org.nongnu.gsequencer.gsequencer.json

* further improvements to pitch

new upstream v3.4.7

---

org.nongnu.gsequencer.gsequencer.json

* fixed arithmetic exception and improved base note of ags_filter_util.c

new upstream v3.4.8

---

org.nongnu.gsequencer.gsequencer.json

* improved ags_filter_util.c to use fmod() to compute phase

new upstream v3.4.9

---

org.nongnu.gsequencer.gsequencer.json

Another change to the plugin support. There is a new unified extension point to simplify a lot of things
- Currently this doesn't change anything on your side (i tested it)
- CMT will be moved to the extension point.
- The older ones will be removed when time comes (for sure when there is the new runtime)
Thanks

Use unified extension point

---

org.nongnu.gsequencer.gsequencer.json

* improved thread-safety of ags/audio/file/*
* improved ags_sf2_synth_util.c and ags_sfz_synth_util.c

new upstream v3.4.10

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.4.11

---

org.nongnu.gsequencer.gsequencer.json

* implemented AgsOnlineHelpWindow
* implemented AgsQuitDialog

new upstream v3.5.0

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.5.2

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.5.5

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.5.8

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.5.9

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.5.10

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing reset of notation edit's horizontal scrollbar after zoom change

new upstream v3.5.12

---

org.nongnu.gsequencer.gsequencer.json

* fixed AgsDssiBridge accessing integer as string

new upstream v3.5.13

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing loop of machines

new upstream v3.5.14

---

org.nongnu.gsequencer.gsequencer.json

* fixed NULL pointer dereference

new upstream v3.5.15

---

org.nongnu.gsequencer.gsequencer.json

The last one have been renamed so these extension point are no longer needed.

Removed legacy extension point

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing AgsMutable interface of ags-fx-volume

new upstream v3.5.16

---

org.nongnu.gsequencer.gsequencer.json

* implemented AgsGstreamerFile capable of reading/writing common media file types mp3, mp4, webm, mkv ...
* minor bug-fixes and improvements

new upstream v3.6.1

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.6.3

---

org.nongnu.gsequencer.gsequencer.json

* added some getter/setter functions to AgsPiano
* minor improvements, fixed potential memory read buffer-overflow.

new upstream v3.6.6

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.6.7

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.6.9

---

org.nongnu.gsequencer.gsequencer.json

* fixed double free recalls of Ags\*DssiBridge Ags\*Lv2Bridge

new upstream v3.6.11

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.6.14

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.6.20

---

org.nongnu.gsequencer.gsequencer.json

* improved notation, automation and wave editor to do proper GUI scale

new upstream v3.6.21

---

org.nongnu.gsequencer.gsequencer.json

* fixed upper of AgsNotationEdit's AgsRuler

new upstream v3.6.22

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.6.29

---

org.nongnu.gsequencer.gsequencer.json

* fixed pitch samples by adjusting volume

new upstream v3.7.0

---

org.nongnu.gsequencer.gsequencer.json

* improved AgsFFPlayer and AgsPitchSampler

new upstream v3.7.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed delay and attack compensation

new upstream v3.7.6

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.7.8

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.7.15

---

org.nongnu.gsequencer.gsequencer.json

* fixed some reference counters

new upstream v3.7.21

---

org.nongnu.gsequencer.gsequencer.json

* fixed accessing string after free

new upstream v3.7.22

---

org.nongnu.gsequencer.gsequencer.json

* added German and French translation of UI
*  fixed uninitialized value in ags_gstreamer_file.c

new upstream v3.7.24

---

org.nongnu.gsequencer.gsequencer.json

* fixed restore of bank-0 and bank-1 of AgsDrum and AgsMatrix from XML
* fixed restore of lower of AgsFMSynth from XML

new upstream v3.7.25

---

org.nongnu.gsequencer.gsequencer.json

* fixed oscillator "control-changed" connect after restore from XML

new upstream v3.7.26

---

org.nongnu.gsequencer.gsequencer.json

* fixed pulseaudio concurrency problems

new upstream v3.7.32

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.7.40

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.7.41

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.7.42

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.7.47

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing loop information of machines

new upstream v3.7.49

---

org.nongnu.gsequencer.gsequencer.json

* fixed connect callback AgsMachine::map-recall() after

Advanced Gtk+ Sequencer v3.7.50

---

org.nongnu.gsequencer.gsequencer.json

* fixed many deprecated Gtk+ symbols
* implemented additional volume controls of AgsFFPlayer, AgsPitchSampler, AgsSyncsynth, AgsFMSyncsynth and AgsMatrix
* important bug-fixes

new upstream v3.8.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed ags_lfo_synth_util.c
* fixed piano playback within notation editor

new upstream v3.8.5

---

org.nongnu.gsequencer.gsequencer.json

* improved stability by using safer dispose and finalize functions in libags_audio.so
* improved AgsPluginBrowser reset combo boxes

new upstream v3.8.6

---

org.nongnu.gsequencer.gsequencer.json

* fixed ags-fx-lfo default values
* fixed wrong tuning of AgsSF2SynthGenerator and AgsSFZSynthGenerator

new upstream v3.8.8

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.8.10

---

org.nongnu.gsequencer.gsequencer.json

* improved to pitch by using Fluidsynth functions included by libags_audio.so

new upstream v3.8.12

---

org.nongnu.gsequencer.gsequencer.json

* select pitch function from UI

new upstream v3.9.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed SIGSEGV with AgsPitchSampler

new upstream v3.9.3

---

gtkmm.yaml
modules/boost.json
org.nongnu.gsequencer.gsequencer.json
patches/gsequencer.patch
patches/vst3sdk.patch

updated upstream version to v3.10.11

---

org.nongnu.gsequencer.gsequencer.json

* implemented VST3 parameter changes

new upstream v3.10.18

---

org.nongnu.gsequencer.gsequencer.json

* fixed editing VST3 controls
* improved threading support for VST3 plugins effect processor ags-fx-vst3

new upstream v3.11.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed restore from XML muted audio

new upstream v3.11.2

---

org.nongnu.gsequencer.gsequencer.json

* improved disable input of VST3 instruments

new upstream v3.11.3

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.11.6

---

org.nongnu.gsequencer.gsequencer.json

* implemented composite editor, this is an all-in-one editor :-)

new upstream v3.12.2

---

org.nongnu.gsequencer.gsequencer.json

* implemented time stretch utility functions

new upstream v3.13.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed wave form editor clipboard

new upstream v3.13.1

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.14.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing automation of fx effect processors

new upstream v3.14.5

---

org.nongnu.gsequencer.gsequencer.json

* fixed wave form editor cursor

new upstream v3.14.7

---

org.nongnu.gsequencer.gsequencer.json

* fixed wave form editor paste from clipboard
* fixed AgsHybridSynth write XML synth sync attack and phase

new upstream v3.14.8

---

org.nongnu.gsequencer.gsequencer.json

* fixed wave form editor selection tool

new upstream v3.14.9

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.14.10

---

org.nongnu.gsequencer.gsequencer.json

* fixed stop AgsAudiorec after export completed

new upstream v3.14.11

---

org.nongnu.gsequencer.gsequencer.json

* fixed AgsSynthUtil and AgsFMSynthUtil missing scale

new upstream v3.15.3

---

org.nongnu.gsequencer.gsequencer.json

* icons with reverse domain notation

new upstream v3.15.4

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.15.5

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.15.6

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.16.0

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.16.1

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.16.2

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.16.3

---

org.nongnu.gsequencer.gsequencer.json

* added fluid custom filter to AgsSF2SynthUtil

new upstream v3.16.4

---

org.nongnu.gsequencer.gsequencer.json

* fixed restore AgsFFPlayer from XML making Soundfont2 load properly

new upstream v3.16.5

---

org.nongnu.gsequencer.gsequencer.json

* fixed AgsSF2Synth missing programs

new upstream v3.16.6

---

org.nongnu.gsequencer.gsequencer.json

* improved AgsSimpleFile to notify about failed plugin load

new upstream v3.16.7

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.16.12

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.16.13

---

org.nongnu.gsequencer.gsequencer.json

* fixed AgsSF2Synth potential SIGSEGV

new upstream v3.16.14

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.17.0

---

org.nongnu.gsequencer.gsequencer.json

new upstream v3.17.5

---

org.nongnu.gsequencer.gsequencer.json

* implemented AgsMetaDataWindow
* implemented hamburger menu

new upstream v3.18.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed GPL-3 license location
* fixed application ID

new upstream v3.18.2

---

gtkmm.yaml
org.nongnu.gsequencer.gsequencer.json
patches/vst3sdk-gcc11.patch

Update to GNOME 42

---

org.nongnu.gsequencer.gsequencer.json

* migrated to libgtk-4
* migrated to libsoup-3.0
* UI improvements
* fixed wave edit clipboard

new upstream major release v4.0.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed machine selector XML IO

new upstream v4.0.7

---

org.nongnu.gsequencer.gsequencer.json

* fixed machine's input dialogs

new upstream v4.0.8

---

org.nongnu.gsequencer.gsequencer.json

new upstream v4.0.12

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing destination of AgsHybridSynth, AgsHybridFMSynth, AgsSF2Synth and AgsSFZSynth chorus

new upstream v4.0.13

---

org.nongnu.gsequencer.gsequencer.json

* implemented presets dialog
* implemented zoom of PDF manual
* implemented print of PDF manual

new upstream v4.1.0

---

org.nongnu.gsequencer.gsequencer.json

new upstream v4.2.1

---

org.nongnu.gsequencer.gsequencer.json

new upstream v4.2.2

---

org.nongnu.gsequencer.gsequencer.json

* implemented no-update UI while refreshing port

new upstream v4.2.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed export soundcard stop callback

new upstream v4.2.4

---

org.nongnu.gsequencer.gsequencer.json

* fixed notation edit delete note

new upstream v4.2.5

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer v4.2.6

---

org.nongnu.gsequencer.gsequencer.json

* fixed Synth and FM Synth parent accessor
* fixed XML restore of machine selector unitialized value

new upstream v4.2.8

---

org.nongnu.gsequencer.gsequencer.json

new upstream v4.2.10

---

org.nongnu.gsequencer.gsequencer.json

new upstream v4.2.11

---

org.nongnu.gsequencer.gsequencer.json

* fixed machine selector
* fixed machine show/hide

new upstream v4.2.12

---

org.nongnu.gsequencer.gsequencer.json

* reverted missing pulseaudio server

new upstream v4.3.0

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v4.3.2

---

org.nongnu.gsequencer.gsequencer.json

* improved thread-safety of some synths

Advanced Gtk+ Sequencer new upstream v4.4.2

---

org.nongnu.gsequencer.gsequencer.json

* additional content in user manual

Advanced Gtk+ Sequencer new upstream v4.4.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing changed event of AgsDial

Advanced Gtk+ Sequencer v4.5.3

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream v5.0.0

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream v5.1.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing persistence of program

Advanced Gtk+ Sequencer new upstream v5.1.1

---

org.nongnu.gsequencer.gsequencer.json

* implemented persistence of dialog model
* fixed automation persistence
* fixed machine selector

Advanced Gtk+ Sequencer new upstream v5.1.2

---

org.nongnu.gsequencer.gsequencer.json

* fixed AgsHybridFMSynth OSC1 volume

Advanced Gtk+ Sequencer new upstream v5.1.5

---

org.nongnu.gsequencer.gsequencer.json

* fixed restore of closed dialogs
* fixed preset editor persistence and update UI

Advanced Gtk+ Sequencer new upstream v5.1.6

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream v5.2.4

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream v5.2.5

---

org.nongnu.gsequencer.gsequencer.json

* implemented format and samplerate setting in machine editor dialog
* implemented format and samplerate information in machine editor input line
* refactored ags-fx-ladspa, ags-fx-dssi and ags-fx-vst3

Advanced Gtk+ Sequencer new upstream v5.3.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed simple file XML read/write of some instrument fields

Advanced Gtk+ Sequencer new upstream v5.3.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed automation edit scrollbar

Advanced Gtk+ Sequencer new upstream v5.3.5

---

org.nongnu.gsequencer.gsequencer.json

* fixed ramp acceleration dialog apply

Advanced Gtk+ Sequencer new upstream v5.3.7

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream v5.3.8

---

org.nongnu.gsequencer.gsequencer.json

* fixed automation editor
* fixed tempo editor

Advanced Gtk+ Sequencer new upstream v5.3.10

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream v5.3.11

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV automation editor
* fixed potential SIGSEGV VST3 bridge
* updated PDF manual screenshots

Advanced Gtk+ Sequencer new upstream v5.3.12

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream v5.4.0

---

org.nongnu.gsequencer.gsequencer.json

improved tempo editor

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v5.4.3

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v5.5.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential buffer overflow

new upstream Advanced Gtk+ Sequencer v5.5.3

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v6.0.3

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v6.0.4

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v6.0.5

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v6.0.6

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v6.0.8

---

org.nongnu.gsequencer.gsequencer.json

Remove jack

---

org.nongnu.gsequencer.gsequencer.json

* implemented note support 256th offset in UI and backend

new upstream Advanced Gtk+ Sequencer v6.1.1

---

org.nongnu.gsequencer.gsequencer.json
patches/vst3sdk-public.patch

- remove unused bits in the manifest

Update to GNOME 45

---

org.nongnu.gsequencer.gsequencer.json

* implemented true note 256th audio processing engine

new upstream Advanced Gtk+ Sequencer v6.2.2

---

org.nongnu.gsequencer.gsequencer.json

* fixed g_strtod() in AgsSimpleFile

new upstream Advanced Gtk+ Sequencer v6.2.5

---

org.nongnu.gsequencer.gsequencer.json

* implemented auto-scroll
* refactored refresh rate by using AgsUiProvider::update-ui()

new upstream Advanced Gtk+ Sequencer 6.4.2

---

org.nongnu.gsequencer.gsequencer.json

* refactored AgsPatternEnvelope
* minor bug-fixes

new upstream Advanced Gtk+ Sequencer 6.4.3

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer 6.4.4

---

org.nongnu.gsequencer.gsequencer.json

* fixed notation, automation and wave edit selection
* various improvements

new upstream Advanced Gtk+ Sequencer 6.5.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed notation scrolled window

new upstream Advanced Gtk+ Sequencer version 6.7.1

---

org.nongnu.gsequencer.gsequencer.json

* implemented --enable-flatpak-sandbox configure switch compiling conditional code

new upstream Advanced Gtk+ Sequencer version 6.8.1

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer version 6.8.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed automation editor cursor

new upstream Advanced Gtk+ Sequencer version 6.8.4

---

org.nongnu.gsequencer.gsequencer.json

* implemented automation render mode

new upstream Advanced Gtk+ Sequencer version 6.8.5

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 6.10.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed bugs introduced while refactoring of dialogs

new upstream Advanced Gtk+ Sequencer version 6.11.5

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 6.12.1

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 6.12.2

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 6.12.5

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 6.14.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed concurrent counter bug

new upstream Advanced Gtk+ Sequencer version 6.14.2

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 6.16.5

---

org.nongnu.gsequencer.gsequencer.json

* improved AgsSimpleFile restore

new upstream Advanced Gtk+ Sequencer version 6.16.8

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer version 6.16.10

---

org.nongnu.gsequencer.gsequencer.json

* improved SMF import
* refactored quit dialog

Advanced Gtk+ Sequencer new upstream v6.16.19

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream version 7.1.3

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream version 7.2.6

---

org.nongnu.gsequencer.gsequencer.json

* fixed file dialog
* improved signal handling of check and toggle button, listen to active property

Advanced Gtk+ Sequencer new upstream version 7.2.11

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 7.4.4

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer version 7.4.9

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential buffer-overflow

new upstream Advanced Gtk+ Sequencer version 7.6.4

---

org.nongnu.gsequencer.gsequencer.json

* fixed multi selection model of drum open dialog

Advanced Gtk+ Sequencer new upstream version 7.6.10

---

org.nongnu.gsequencer.gsequencer.json

* improved wave form clipboard

Advanced Gtk+ Sequencer new upstream version 7.6.14

---

org.nongnu.gsequencer.gsequencer.json

* fixed wave form editor clipboard

Advanced Gtk+ Sequencer new upstream version 7.6.16

---

org.nongnu.gsequencer.gsequencer.json

* implemented new Raven Synthesizer subtractive synth

Advanced Gtk+ Sequencer new upstream version 7.7.0

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream version 7.7.1

---

org.nongnu.gsequencer.gsequencer.json

Advanced Gtk+ Sequencer new upstream version 7.7.5

---

org.nongnu.gsequencer.gsequencer.json

* improved program stability
* fixed multi-channel restore from XML project file

Advanced Gtk+ Sequencer v8.0.10

---

org.nongnu.gsequencer.gsequencer.json

* fixed piano roll drawing bug

Advanced Gtk+ Sequencer new upstream version 8.0.14

---

org.nongnu.gsequencer.gsequencer.json

* some performance improvements

Advanced Gtk+ Sequencer new upstream version 8.1.5
