flathub/org.nongnu.gsequencer.gsequencer

org.nongnu.gsequencer.gsequencer.json

* improved iterating buffer in ags_audio_buffer_util.c
* work-around for broken lock-free audio buffer, reverted see below
* reverted ags_devout.c to 2.2.25
* reverted ags_play_audio_signal.c to 2.2.25

new upstream v2.2.36

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV caused by AgsFFPlayer's input bridge
* fixed accessing freed memory of AgsBulkMember

new upstream v2.4.4

---

org.nongnu.gsequencer.gsequencer.json

* fixed greedy ags-lv2 and ags-dssi recall

GSequencer v3.2.13

---

org.nongnu.gsequencer.gsequencer.json

This add support for Linux Audio plugins: LADSPA, LV2, and DSSI.
Currently waiting to land are swh flathub/flathub#1504 and SoSynth flathub/flathub#1459
Many more in the queue.
When CMT lands, it can be removed from this build and tell to install the plugins as a flatpak automatically (I'll submit a PR in time).
Note: I did not add VST and VST3 support. But it is possible too.

Add support for Audio plugins

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential dead-lock of ags-fx-ladspa and ags-fx-lv2
* fixed missing reverse mapping
* fixed missing AgsBulkMember ports

new upstream v3.3.2

---

org.nongnu.gsequencer.gsequencer.json

Also update shared modules.
From here, it is possible to support JACK through Pipewire

Update runtime to GNOME 3.38

---

org.nongnu.gsequencer.gsequencer.json

* fixed use ags-fx instead deprecated recalls in ags_simple_file.c
* fixed wrong type cast with interface in ags_xorg_application_context.c

new upstream v3.7.30

---

org.nongnu.gsequencer.gsequencer.json

* fixed ags_hq_pitch_util.c passed wrong factor to interpolate, affecting AgsFFPlayer and AgsPitchSampler

new upstream v3.8.11

---

org.nongnu.gsequencer.gsequencer.json

This should allow JACK to work. Previously it would never.
Also updated the runtime to GNOME 40 and the shared-modules.

Add jack support via Pipewire

---

org.nongnu.gsequencer.gsequencer.json

* implemented AgsVst3Browser allowing you to assign VST3 plugin to AgsLine, AgsEffectLine and AgsEffectBulk

new upstream v3.10.12

---

org.nongnu.gsequencer.gsequencer.json

* fixed SIGSEGV after destroy AgsLiveVst3Bridge
* fixed parallelism by running all the components of an instance from the very same thread

new upstream v3.11.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed SIGABRT while terminating GSequencer
* implemented AgsAlsaDevout, AgsAlsaDevin and AgsAlsaMidiin
* implemented AgsOssDevout, AgsOssDevin and AgsOssMidiin
* deprecated AgsDevout, AgsDevin and AgsMidiin

new upstream v3.13.3

---

org.nongnu.gsequencer.gsequencer.json

*  fixed missing configure_event callback to reset scrollbars of composite edit

new upstream v3.15.2

---

org.nongnu.gsequencer.gsequencer.json

* fixed ref count of ags-fx-ladspa, ags-fx-dssi, ags-fx-lv2 and ags-fx-vst3

new upstream v3.16.8

---

org.nongnu.gsequencer.gsequencer.json

* disabled webkit2gtk-4.0 dependency per default
* fixed SIGSEGV with AgsExportWindow

Advanced Gtk+ Sequencer v3.19.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV with AgsEffectLine while removing plugin

Advanced Gtk+ Sequencer v4.2.14

---

org.nongnu.gsequencer.gsequencer.json

* fixed SIGSEGV with AgsSF2SynthUtil resample
* fixed premature stop of playback after file export

Advanced Gtk+ Sequencer new upstream v4.4.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed octave upper and lower of ags-fx-sf2 and ags-fx-sfz

Advanced Gtk+ Sequencer new upstream v5.0.2

---

org.nongnu.gsequencer.gsequencer.json

* fixes to AgsLiveLv2Bridge
* additional controls for AgsSF2Synth and AgsSFZSynth

Advanced Gtk+ Sequencer new upstream v5.2.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed default values of AgsSF2Synth and AgsSFZSynth
* fixed missing callbacks of AgsSF2Synth and AgsSFZSynth

Advanced Gtk+ Sequencer new upstream v5.2.3

---

org.nongnu.gsequencer.gsequencer.json

* improved libsndfile resampling respect minimum buffer size

new upstream Advanced Gtk+ Sequencer v6.0.7

---

org.nongnu.gsequencer.gsequencer.json

* fixed SFZ synth format and resampling

new upstream Advanced Gtk+ Sequencer v6.0.9

---

org.nongnu.gsequencer.gsequencer.json

* fixed double free with VST3 plugin

new upstream Advanced Gtk+ Sequencer v6.0.11

---

org.nongnu.gsequencer.gsequencer.json

* fixed ags-fx-playback and ags-fx-buffer resampling

new upstream Advanced Gtk+ Sequencer v6.0.12

---

org.nongnu.gsequencer.gsequencer.json

new upstream Advanced Gtk+ Sequencer v6.0.13

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV with failed alsa playback

new upstream Advanced Gtk+ Sequencer v6.1.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV while saving XML files
* refactored ags-fx-buffer
* implemented note 256th attack on soundcard

new upstream Advanced Gtk+ Sequencer v6.2.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed soundcard interface access in ags-fx-notation

new upstream Advanced Gtk+ Sequencer v6.2.3

---

org.nongnu.gsequencer.gsequencer.json

* implemented note 256th attack of 16th pulse
* refactored ags-fx-notation
* refactored all soundcard implementations

new upstream Advanced Gtk+ Sequencer 6.3.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed double free in ags_audio_remove_automation_port()
* fixed potential SIGSEGV with automation editor

new upstream Advanced Gtk+ Sequencer version 6.7.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed memory leaks in effect processing engine

new upstream Advanced Gtk+ Sequencer version 6.7.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed dead-lock with pulseaudio

new upstream Advanced Gtk+ Sequencer version 6.8.6

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing playback of notes due to bug in counters of ags-fx-notation and AgsSoundcard implementations

new upstream Advanced Gtk+ Sequencer version 6.9.0

---

org.nongnu.gsequencer.gsequencer.json

* fixed SMF import/export
* refactored tool dialogs to popovers

new upstream Advanced Gtk+ Sequencer version 6.11.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed clear machine selector menu after open file

new upstream Advanced Gtk+ Sequencer version 6.14.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed loop and timing
* fixed potential SIGSEGV while filename not supplied

new upstream Advanced Gtk+ Sequencer version 6.15.3

---

org.nongnu.gsequencer.gsequencer.json

* improved open file, missing plugin caused SIGSEGV
* improved notation edit missing note 256th support caused corrupted notation while keyboard editing

Advanced Gtk+ Sequencer v6.15.4

---

org.nongnu.gsequencer.gsequencer.json

* improved lost first note with pulseaudio or JACK

new upstream Advanced Gtk+ Sequencer version 6.16.1

---

org.nongnu.gsequencer.gsequencer.json

* fixed missing confirm dialog to remove existing files while audio file export.

new upstream Advanced Gtk+ Sequencer version 6.16.2

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential buffer overflow with new pitch utility functions

new upstream Advanced Gtk+ Sequencer version 6.16.3

---

org.nongnu.gsequencer.gsequencer.json

* fixed infinite loop with wave form cut

new upstream Advanced Gtk+ Sequencer version 6.16.6

---

org.nongnu.gsequencer.gsequencer.json

* fixed SIGSEGV while XML project file restore
* improved XML project file synth update during restore

Advanced Gtk+ Sequencer version 6.16.11

---

org.nongnu.gsequencer.gsequencer.json

* fixed race condition with AgsSF2Synth MIDI locale loader

Advanced Gtk+ Sequencer version 6.16.16

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV while shrinking audio channels with assigned audio files

Advanced Gtk+ Sequencer new upstream v6.16.21

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV while shrinking AgsAudio related to g_object_run_dispose()

Advanced Gtk+ Sequencer new upstream v6.16.22

---

org.nongnu.gsequencer.gsequencer.json

* new major release
* fixed potential SIGSEGV with AgsMidiPreferences remove sequencer editor
* improved audio/MIDI configuration in AgsPreferences
* code improvements

Advanced Gtk+ Sequencer new upstream version 7.0.12

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential buffer-overflow

Advanced Gtk+ Sequencer new upstream version 7.2.4

---

org.nongnu.gsequencer.gsequencer.json

* fixed wave form editor clipboard

Advanced Gtk+ Sequencer new upstream version 7.6.18

---

org.nongnu.gsequencer.gsequencer.json

* fixed AgsAudioTreeDispatcher wrong ref-counter

Advanced Gtk+ Sequencer new upstream version 8.0.8

---

org.nongnu.gsequencer.gsequencer.json

* fixed potential SIGSEGV of composite editor popovers
* fixed automation editor restore from XML project files

Advanced Gtk+ Sequencer new upstream version 8.1.1
